//! Unreal C++ output. Generated code depends on the schemas only, never on data values.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::excel::DataModel;
use crate::i18n::tr;
use crate::schema::{enum_of, fixed_of, in_scopes, ColumnSchema, EnumSchema, Enums, TableSchema, CLIENT_SCOPES};
use crate::value::{json_string, py_float_repr, Value};
use crate::values::default_value;

pub const DEFAULT_ASSET_BASE: &str = "UPrimaryDataAsset";
pub const DEFAULT_ASSET_BASE_HEADER: &str = "Engine/DataAsset.h";
pub const DEFAULT_ASSET_NAME: &str = "DA_{table}";

fn cpp_type_of(type_name: &str, prefix: &str) -> String {
    if let Some((_, wide)) = fixed_of(type_name) {
        return if wide { "int64" } else { "int32" }.to_string();
    }
    if let Some(rest) = type_name.strip_prefix('E') {
        return format!("E{prefix}{rest}");
    }
    match type_name {
        "name" => "FName",
        "string" => "FString",
        "text" => "FText",
        "tag" => "FGameplayTag",
        "path" => "FSoftObjectPath",
        other => other,
    }
    .to_string()
}

fn cpp_type(column: &ColumnSchema, prefix: &str) -> String {
    cpp_type_of(&column.type_name, prefix)
}

fn type_include(type_name: &str) -> Option<&'static str> {
    match type_name {
        "text" => Some("Internationalization/Text.h"),
        "tag" => Some("GameplayTagContainer.h"),
        "path" => Some("UObject/SoftObjectPath.h"),
        _ => None,
    }
}

/// Writes the C++ headers. With `runtime_header`, also the runtime integration: row lookups
/// and reference accessors, one .cpp per table and the registration header.
pub fn emit_cpp(
    model: &DataModel,
    output: &Path,
    prefix: &str,
    asset_base: &str,
    asset_base_header: Option<&str>,
    runtime_header: Option<&str>,
    asset_name: &str,
) -> std::io::Result<()> {
    std::fs::create_dir_all(output)?;
    let header = asset_base_header.unwrap_or(DEFAULT_ASSET_BASE_HEADER);
    for e in &model.enums {
        write(&output.join(format!("E{prefix}{}.h", e.name)), &enum_header(e, prefix))?;
    }
    let enums = model.enum_map();
    for table in model.data_tables() {
        write(&output.join(format!("{prefix}{}Row.h", table.name)), &table_header(table, prefix, &enums, runtime_header.is_some()))?;
        write(&output.join(format!("{prefix}{}Table.h", table.name)), &asset_header(table, prefix, asset_base, header))?;
        if let Some(runtime) = runtime_header {
            write(&output.join(format!("{prefix}{}Row.cpp", table.name)), &row_source(table, prefix, runtime))?;
        }
    }
    write(&output.join(format!("{prefix}GeneratedTables.h")), &tables_header(model, prefix))?;
    if !model.aliases.is_empty() {
        write(&output.join(format!("{prefix}Types.h")), &types_header(model, prefix))?;
    }
    if runtime_header.is_some() {
        write(&output.join(format!("{prefix}TableRegistration.h")), &registration_header(model, prefix, asset_name))?;
    }
    Ok(())
}

/// The first comment line, naming where the definition lives.
fn source_line(sources: &[String], sheet: Option<&str>) -> String {
    if sources.len() > 1 {
        let parts: String = sources.iter().map(|s| format!("\n//   {s}")).collect();
        return format!("// Generated by DrTableSystem. Do not edit. Sources:{parts}");
    }
    let name = sources.first().map(String::as_str).unwrap_or("");
    match sheet {
        Some(sheet) if !sheet.is_empty() => format!("// Generated by DrTableSystem. Do not edit. Source: {name} / {sheet}"),
        _ => format!("// Generated by DrTableSystem. Do not edit. Source: {name}"),
    }
}

fn table_source_line(table: &TableSchema) -> String {
    if table.schema_file.is_empty() {
        source_line(&table.source_list(), None)
    } else {
        source_line(std::slice::from_ref(&table.schema_file), None)
    }
}

fn enum_header(e: &EnumSchema, prefix: &str) -> String {
    let mut lines = vec![
        source_line(std::slice::from_ref(&e.source_name), Some(&e.sheet)),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        format!("#include \"E{prefix}{}.generated.h\"", e.name),
        String::new(),
        "UENUM(BlueprintType)".into(),
        format!("enum class E{prefix}{} : uint8", e.name),
        "{".into(),
    ];
    for value in &e.values {
        let suffix = if value.comment.is_empty() { String::new() } else { format!(" // {}", cpp_comment(&value.comment)) };
        lines.push(format!("    {} = {},{suffix}", value.name, value.value));
    }
    lines.extend(["};".into(), String::new()]);
    lines.join("\n")
}

fn client_columns(table: &TableSchema) -> impl Iterator<Item = &ColumnSchema> {
    table.columns.iter().filter(|c| in_scopes(&c.scope, &CLIENT_SCOPES))
}

fn table_header(table: &TableSchema, prefix: &str, enums: &Enums, accessors: bool) -> String {
    let enum_includes: BTreeSet<&str> = client_columns(table).filter_map(|c| c.type_name.strip_prefix('E')).collect();
    let type_includes: BTreeSet<&str> = client_columns(table).filter_map(|c| type_include(&c.type_name)).collect();
    let mut lines = vec![
        table_source_line(table),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        "#include \"Engine/DataTable.h\"".into(),
    ];
    lines.extend(type_includes.iter().map(|h| format!("#include \"{h}\"")));
    lines.extend(enum_includes.iter().map(|n| format!("#include \"E{prefix}{n}.h\"")));
    lines.push(format!("#include \"{prefix}{}Row.generated.h\"", table.name));
    if accessors {
        let targets = ref_targets(table);
        if !targets.is_empty() {
            lines.push(String::new());
            lines.extend(targets.iter().map(|t| format!("struct F{prefix}{t}Row;")));
        }
    }
    lines.extend([
        String::new(),
        "USTRUCT(BlueprintType)".into(),
        format!("struct F{prefix}{}Row : public FTableRowBase", table.name),
        "{".into(),
        "    GENERATED_BODY()".into(),
        String::new(),
    ]);
    for column in client_columns(table) {
        let specifiers = if column.is_array() { "EditAnywhere" } else { "EditAnywhere, BlueprintReadOnly" };
        let mut meta: Vec<String> = Vec::new();
        if let Some(target) = &column.ref_target {
            meta.push(format!("TableRef = \"{target}\""));
            if let Some(key) = &column.ref_key {
                meta.push(format!("TableRefKey = \"{key}\""));
            }
        }
        if let Some((scale, _)) = fixed_of(&column.type_name) {
            meta.push(format!("DrFixedScale = \"{scale}\""));
        }
        if let Some(alias) = &column.alias {
            meta.push(format!("DrType = \"{alias}\""));
        }
        let metadata = if meta.is_empty() { String::new() } else { format!(", meta = ({})", meta.join(", ")) };
        lines.push(format!("    UPROPERTY({specifiers}, Category = \"{prefix}|{}\"{metadata})", table.name));
        let mut declaration = format!("{} {}", cpp_type(column, prefix), column.name);
        if let Some(size) = column.array_size {
            declaration += &format!("[{size}]");
            if column.default_values.iter().any(Option::is_some) {
                let values: Vec<String> = column
                    .default_values
                    .iter()
                    .map(|value| {
                        let value = value.clone().unwrap_or_else(|| default_value(&column.type_name, enums));
                        cpp_value(&column.type_name, &value, prefix)
                    })
                    .collect();
                declaration += &format!(" = {{{}}}", values.join(", "));
            } else {
                declaration += " = {}";
            }
        } else {
            declaration += &cpp_initializer(column, prefix, enums);
        }
        lines.push(format!("    {declaration};"));
        if let Some((scale, wide)) = fixed_of(&column.type_name) {
            // Stored in 1/scale units: 1234 means 0.1234 for fixed<10000>.
            lines.push(format!("    static constexpr {} {}Scale = {scale};", if wide { "int64" } else { "int32" }, column.name));
        }
        lines.push(String::new());
    }
    if accessors {
        lines.extend(accessor_declarations(table, prefix));
    }
    lines.extend(["};".into(), String::new()]);
    lines.join("\n")
}

fn client_refs(table: &TableSchema) -> Vec<&ColumnSchema> {
    table.columns.iter().filter(|c| c.ref_target.is_some() && in_scopes(&c.scope, &CLIENT_SCOPES)).collect()
}

fn client_sub_keys(table: &TableSchema) -> Vec<&ColumnSchema> {
    table.columns.iter().filter(|c| c.is_role("subkey") && in_scopes(&c.scope, &CLIENT_SCOPES)).collect()
}

/// Other tables this row references (excluding itself and string tables), sorted by name.
fn ref_targets(table: &TableSchema) -> BTreeSet<String> {
    client_refs(table)
        .into_iter()
        .filter(|c| !c.ref_strings)
        .filter_map(|c| c.ref_target.clone())
        .filter(|t| *t != table.name)
        .collect()
}

fn ref_return(column: &ColumnSchema, prefix: &str) -> String {
    if column.ref_strings {
        return "FText".into();
    }
    let row = format!("F{prefix}{}Row", column.ref_target.as_deref().unwrap_or(""));
    if column.ref_key.is_some() { format!("TArray<const {row}*>") } else { format!("const {row}*") }
}

fn accessor_declarations(table: &TableSchema, prefix: &str) -> Vec<String> {
    let row = format!("F{prefix}{}Row", table.name);
    let mut lines = vec![
        "    // Lookups (generated). Resolved through the DrTableRuntime contract.".to_string(),
        format!("    static const {row}* Find({} Key);", cpp_type(table.primary_key(), prefix)),
    ];
    for column in client_sub_keys(table) {
        lines.push(format!("    static TArray<const {row}*> FindBy{}({} Key);", column.name, cpp_type(column, prefix)));
    }
    lines.push(format!("    static TConstArrayView<{row}> GetAll();"));
    let refs = client_refs(table);
    if !refs.is_empty() {
        lines.extend([
            String::new(),
            "    // Reference accessors (generated). An empty reference (0 / NAME_None) returns without a lookup.".to_string(),
        ]);
    }
    for column in refs {
        let argument = if column.is_array() { "int32 Index" } else { "" };
        lines.push(format!("    {} Get{}({argument}) const;", ref_return(column, prefix), column.name));
    }
    lines.push(String::new());
    lines
}

/// Member function names the row struct gets with runtime integration, with the header cell
/// that caused each.
pub fn generated_member_names(table: &TableSchema) -> Vec<(String, String)> {
    let primary_cell = table.primary_key().header_cells[0].clone();
    let mut names = vec![("Find".to_string(), primary_cell.clone()), ("GetAll".to_string(), primary_cell)];
    names.extend(client_sub_keys(table).iter().map(|c| (format!("FindBy{}", c.name), c.header_cells[0].clone())));
    names.extend(client_refs(table).iter().map(|c| (format!("Get{}", c.name), c.header_cells[0].clone())));
    names
}

fn absent_check(column: &ColumnSchema, expression: &str) -> Option<String> {
    match column.type_name.as_str() {
        "int32" | "int64" => Some(format!("{expression} == 0")),
        "name" => Some(format!("{expression}.IsNone()")),
        _ => None,
    }
}

fn row_source(table: &TableSchema, prefix: &str, runtime_header: &str) -> String {
    let row = format!("F{prefix}{}Row", table.name);
    let mut lines = vec![table_source_line(table), format!("#include \"{prefix}{}Row.h\"", table.name)];
    lines.extend(ref_targets(table).iter().map(|t| format!("#include \"{prefix}{t}Row.h\"")));
    lines.extend([format!("#include \"{runtime_header}\""), String::new()]);
    lines.extend([
        format!("const {row}* {row}::Find({} Key)", cpp_type(table.primary_key(), prefix)),
        "{".into(),
        format!("    return DrTableRuntime::FindByKey<{row}>(Key);"),
        "}".into(),
        String::new(),
    ]);
    for column in client_sub_keys(table) {
        lines.extend([
            format!("TArray<const {row}*> {row}::FindBy{}({} Key)", column.name, cpp_type(column, prefix)),
            "{".into(),
            format!("    return DrTableRuntime::FindAllBySubKey<{row}>(FName(TEXT(\"{}\")), Key);", column.name),
            "}".into(),
            String::new(),
        ]);
    }
    lines.extend([
        format!("TConstArrayView<{row}> {row}::GetAll()"),
        "{".into(),
        format!("    return DrTableRuntime::GetAll<{row}>();"),
        "}".into(),
        String::new(),
    ]);
    for column in client_refs(table) {
        let target_row = format!("F{prefix}{}Row", column.ref_target.as_deref().unwrap_or(""));
        let empty = if column.ref_strings {
            "FText::GetEmpty()"
        } else if column.ref_key.is_some() {
            "{}"
        } else {
            "nullptr"
        };
        let lookup = match &column.ref_key {
            Some(key) => format!("FindBy{key}"),
            None => "Find".to_string(),
        };
        let value = if column.is_array() { format!("{}[Index]", column.name) } else { column.name.clone() };
        let mut guards = Vec::new();
        if let Some(size) = column.array_size {
            guards.push(format!("Index < 0 || Index >= {size}"));
        }
        if let Some(absent) = absent_check(column, &value) {
            guards.push(absent);
        }
        let argument = if column.is_array() { "int32 Index" } else { "" };
        lines.extend([format!("{} {row}::Get{}({argument}) const", ref_return(column, prefix), column.name), "{".into()]);
        if !guards.is_empty() {
            lines.extend([
                format!("    if ({})", guards.join(" || ")),
                "    {".into(),
                format!("        return {empty};"),
                "    }".into(),
            ]);
        }
        let result = if column.ref_strings {
            // Text of the current language, through the string table runtime.
            format!("    return DrTableRuntime::GetText(FName(TEXT(\"{}\")), {value});", column.ref_target.as_deref().unwrap_or(""))
        } else {
            format!("    return {target_row}::{lookup}({value});")
        };
        lines.extend([result, "}".into(), String::new()]);
    }
    lines.join("\n")
}

fn registration_header(model: &DataModel, prefix: &str, asset_name: &str) -> String {
    let mut lines = vec![
        "// Generated by DrTableSystem. Do not edit.".to_string(),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        format!("#include \"{prefix}GeneratedTables.h\""),
    ];
    lines.extend(model.data_tables().map(|t| format!("#include \"{prefix}{}Table.h\"", t.name)));
    lines.extend([
        String::new(),
        format!("namespace {prefix}GeneratedTables"),
        "{".into(),
        "    // The registry provides Register<Row, Asset>(Name, RowsMember, PrimaryKeysMember). Its result".into(),
        "    // must chain WithSchemaHash(Hash) and WithSubKey(Name, KeysMember, OffsetsMember,".into(),
        "    // IndicesMember). Generated code depends on the schema only, never on data values.".into(),
        "    template <typename TRegistry>".into(),
        "    void RegisterAll(TRegistry& Registry)".into(),
        "    {".into(),
    ]);
    for table in model.data_tables() {
        let row = format!("F{prefix}{}Row", table.name);
        let asset = format!("U{prefix}{}Table", table.name);
        let name = asset_name.replace("{table}", &table.name);
        lines.push(format!(
            "        Registry.template Register<{row}, {asset}>(TEXT(\"{name}\"), &{asset}::Rows, &{asset}::PrimaryKeys)"
        ));
        lines.push(format!("            .WithSchemaHash({}SchemaHash)", table.name));
        for column in client_sub_keys(table) {
            lines.push(format!(
                "            .WithSubKey(TEXT(\"{0}\"), &{asset}::{0}_Keys, &{asset}::{0}_Offsets, &{asset}::{0}_Indices)",
                column.name
            ));
        }
        if let Some(last) = lines.last_mut() {
            last.push(';');
        }
    }
    lines.extend(["    }".into(), "}".into(), String::new()]);
    lines.join("\n")
}

/// DataAsset class the bake commandlet fills. Indices are computed at build time.
fn asset_header(table: &TableSchema, prefix: &str, asset_base: &str, asset_base_header: &str) -> String {
    let enum_includes: BTreeSet<&str> = client_columns(table).filter_map(|c| c.type_name.strip_prefix('E')).collect();
    let mut lines = vec![
        table_source_line(table),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        format!("#include \"{asset_base_header}\""),
        format!("#include \"{prefix}{}Row.h\"", table.name),
    ];
    lines.extend(enum_includes.iter().map(|n| format!("#include \"E{prefix}{n}.h\"")));
    lines.extend([
        format!("#include \"{prefix}{}Table.generated.h\"", table.name),
        String::new(),
        "UCLASS(BlueprintType)".into(),
        format!("class U{prefix}{}Table : public {asset_base}", table.name),
        "{".into(),
        "    GENERATED_BODY()".into(),
        String::new(),
        "public:".into(),
        "    // All rows in one contiguous array, sorted by primary key.".into(),
        format!("    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = \"{prefix}|{}\")", table.name),
        format!("    TArray<F{prefix}{}Row> Rows;", table.name),
        String::new(),
        "    // Primary keys in the same order as Rows, searched with a binary search.".into(),
        "    UPROPERTY()".into(),
        format!("    TArray<{}> PrimaryKeys;", cpp_type(table.primary_key(), prefix)),
        String::new(),
    ]);
    for column in table.sub_keys() {
        if !in_scopes(&column.scope, &CLIENT_SCOPES) {
            continue;
        }
        let key_type = cpp_type(column, prefix);
        lines.extend([
            format!("    // Sub key {}: CSR index (sorted keys, bucket offsets, row indices).", column.name),
            "    UPROPERTY()".into(),
            format!("    TArray<{key_type}> {}_Keys;", column.name),
            String::new(),
            "    UPROPERTY()".into(),
            format!("    TArray<int32> {}_Offsets;", column.name),
            String::new(),
            "    UPROPERTY()".into(),
            format!("    TArray<int32> {}_Indices;", column.name),
            String::new(),
        ]);
    }
    lines.extend(["};".into(), String::new()]);
    lines.join("\n")
}

fn tables_header(model: &DataModel, prefix: &str) -> String {
    let mut lines = vec![
        "// Generated by DrTableSystem. Do not edit.".to_string(),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        String::new(),
        format!("namespace {prefix}GeneratedTables"),
        "{".into(),
    ];
    for table in model.data_tables() {
        let sub_keys: Vec<&str> = table.sub_keys().iter().map(|c| c.name.as_str()).collect();
        lines.extend([
            format!("    inline constexpr TCHAR {0}Name[] = TEXT(\"{0}\");", table.name),
            format!("    inline constexpr TCHAR {}PrimaryKey[] = TEXT(\"{}\");", table.name, table.primary_key().name),
            format!("    inline constexpr TCHAR {}SubKeys[] = TEXT(\"{}\");", table.name, sub_keys.join(",")),
            format!("    inline constexpr TCHAR {}SchemaHash[] = TEXT(\"{}\");", table.name, table.schema_hash),
            String::new(),
        ]);
    }
    lines.extend(["}".into(), String::new()]);
    lines.join("\n")
}

fn cpp_initializer(column: &ColumnSchema, prefix: &str, enums: &Enums) -> String {
    if let Some(Some(value)) = column.default_values.first() {
        return format!(" = {}", cpp_value(&column.type_name, value, prefix));
    }
    if fixed_of(&column.type_name).is_some() {
        return " = 0".into();
    }
    match column.type_name.as_str() {
        "int32" | "int64" => return " = 0".into(),
        "float" => return " = 0.0f".into(),
        "double" => return " = 0.0".into(),
        "bool" => return " = false".into(),
        _ => {}
    }
    if column.ref_target.is_some() && column.type_name == "name" {
        return " = NAME_None".into();
    }
    if let Some(name) = enum_of(&column.type_name)
        && let Some(first) = enums.get(name).and_then(|e| e.values.first()) {
            return format!(" = E{prefix}{name}::{}", first.name);
        }
    String::new()
}

fn float_text(value: &Value) -> String {
    let number = match value {
        Value::Int(i) => *i as f64,
        Value::Float(f) => *f,
        Value::Bool(b) => *b as i64 as f64,
        _ => 0.0,
    };
    let text = py_float_repr(number);
    if text.contains('.') || text.contains('e') { text } else { format!("{text}.0") }
}

fn cpp_value(type_name: &str, value: &Value, prefix: &str) -> String {
    if fixed_of(type_name).is_some() {
        return value.py_str();
    }
    match type_name {
        "int32" | "int64" => value.py_str(),
        "float" => format!("{}f", float_text(value)),
        "double" => float_text(value),
        "bool" => {
            let truthy = match value {
                Value::Bool(b) => *b,
                Value::Int(i) => *i != 0,
                Value::Float(f) => *f != 0.0,
                Value::Str(s) => !s.is_empty(),
                _ => false,
            };
            if truthy { "true" } else { "false" }.to_string()
        }
        _ => {
            let literal = json_string(&value.py_str());
            match type_name {
                "name" => format!("FName(TEXT({literal}))"),
                "string" => format!("FString(TEXT({literal}))"),
                "text" => format!("FText::FromString(TEXT({literal}))"),
                // Member initializers can run before the tag table is loaded (e.g. CDO
                // construction), so ErrorIfNotFound is false.
                "tag" => format!("FGameplayTag::RequestGameplayTag(FName(TEXT({literal})), false)"),
                "path" => format!("FSoftObjectPath(TEXT({literal}))"),
                t => match t.strip_prefix('E') {
                    Some(rest) => format!("E{prefix}{rest}::{}", value.py_str()),
                    None => String::new(),
                },
            }
        }
    }
}

fn cpp_comment(value: &str) -> String {
    value.replace(['\r', '\n'], " ")
}

fn write(path: &Path, content: &str) -> std::io::Result<()> {
    std::fs::write(path, content)
}

/// Key constants of a string table (`--string-keys`): `<Prefix><Table>Keys::<Key>`. The keys come
/// from the data, so this header changes whenever a key is added or removed. Keys that are not
/// C++ identifiers have other characters replaced with '_'; keys that would share a constant are
/// errors.
pub fn string_keys_header(table: &TableSchema, prefix: &str) -> Result<String, Vec<String>> {
    let key_index = table.columns.iter().position(|c| c.is_role("id")).expect("a primary key");
    let mut keys: Vec<String> = table.rows.iter().filter_map(|row| row[key_index].as_str().map(str::to_string)).collect();
    keys.sort();
    let mut constants: BTreeMap<String, String> = BTreeMap::new();
    let mut errors = Vec::new();
    for key in &keys {
        let mut constant: String = key.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect();
        if !constant.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_') {
            constant.insert(0, '_');
        }
        if let Some(first) = constants.get(&constant) {
            errors.push(tr(
                format!("{}: 키 '{first}'와 '{key}'가 같은 상수 이름 {constant}이 됩니다", table.header_location()),
                format!("{}: keys '{first}' and '{key}' would share the constant name {constant}", table.header_location()),
            ));
            continue;
        }
        constants.insert(constant, key.clone());
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    let mut lines = vec![
        table_source_line(table),
        "// Key constants come from the data (--string-keys): this file changes when keys change.".into(),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
        String::new(),
        format!("namespace {prefix}{}Keys", table.name),
        "{".into(),
    ];
    for (constant, key) in &constants {
        lines.push(format!("    inline constexpr TCHAR {constant}[] = TEXT({});", json_string(key)));
    }
    lines.extend(["}".into(), String::new()]);
    Ok(lines.join("\n"))
}

/// Type aliases for game code (`using DrItemID = int32;`). Row structs use the underlying types,
/// since Unreal reflection does not read typedefs; their properties carry meta = (DrType = "ItemID").
fn types_header(model: &DataModel, prefix: &str) -> String {
    let mut includes: BTreeSet<String> = BTreeSet::new();
    for alias in &model.aliases {
        if let Some(include) = type_include(&alias.type_name) {
            includes.insert(include.to_string());
        }
        if let Some(name) = enum_of(&alias.type_name) {
            includes.insert(format!("E{prefix}{name}.h"));
        }
    }
    let mut lines = vec![
        "// Generated by DrTableSystem. Do not edit. Source: type aliases (*.using.xlsx)".to_string(),
        "#pragma once".into(),
        String::new(),
        "#include \"CoreMinimal.h\"".into(),
    ];
    lines.extend(includes.iter().map(|h| format!("#include \"{h}\"")));
    lines.push(String::new());
    for alias in &model.aliases {
        if !alias.comment.is_empty() {
            lines.push(format!("// {}", alias.comment.replace(['\r', '\n'], " ")));
        }
        lines.push(format!("using {prefix}{} = {};", alias.name, cpp_type_of(&alias.type_name, prefix)));
        if let Some((scale, wide)) = fixed_of(&alias.type_name) {
            lines.push(format!("inline constexpr {} {prefix}{}Scale = {scale};", if wide { "int64" } else { "int32" }, alias.name));
        }
    }
    lines.push(String::new());
    lines.join("\n")
}
