"""한 테이블을 여러 시트·파일로 나누는 기능과 [파일]시트 위치 표기 테스트."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from openpyxl import Workbook

from tablegen.cli import main

HEAD = [["Id", "Name", "Cost"], ["ID<int32>", "name", "int32"], ["all", "all", "server"]]


def _save(path: Path, sheets: dict[str, list[list[object]]]) -> None:
    workbook = Workbook()
    workbook.remove(workbook.active)
    for name, rows in sheets.items():
        sheet = workbook.create_sheet(name)
        for record in rows:
            sheet.append(record)
    path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(path)


def _build(source: Path, root: Path, *extra: str) -> int:
    return main(["build", "--input", str(source), "--out-cpp", str(root / "cpp"),
                 "--out-client", str(root / "client"), "--out-server", str(root / "server"), *extra])


def _rows(root: Path, scope: str, table: str) -> list[dict]:
    return json.loads((root / scope / f"{table}.json").read_text(encoding="utf-8"))["rows"]


def test_table_split_across_sheets_and_files(tmp_path: Path) -> None:
    data = tmp_path / "data"
    _save(data / "Items.xlsx", {"Items@Weapons": [*HEAD, [1, "Sword", 10]],
                                "Items@Armor": [*HEAD, [20, "Mail", 30]]})
    # 다른 폴더·파일의 조각은 열 순서가 달라도 된다.
    _save(data / "event" / "Summer.xlsx", {"Items@Summer": [
        ["Cost", "Id", "Name"], ["int32", "ID<int32>", "name"], ["server", "all", "all"], [5, 3, "Fan"]]})
    assert _build(data, tmp_path / "out") == 0
    rows = _rows(tmp_path / "out", "server", "Items")
    assert [(row["Id"], row["Name"], row["Cost"]) for row in rows] == [
        (1, "Sword", 10), (3, "Fan", 5), (20, "Mail", 30)]
    assert list(rows[1]) == ["Id", "Name", "Cost"]
    header = (tmp_path / "out" / "cpp" / "DtItemsRow.h").read_text(encoding="utf-8")
    assert header.startswith(
        "// Generated by ue-tablegen. Do not edit. Sources:\n"
        "//   Items.xlsx / Items@Weapons\n"
        "//   Items.xlsx / Items@Armor\n"
        "//   event/Summer.xlsx / Items@Summer\n"
        "#pragma once\n")


def test_split_table_matches_unsplit_output(tmp_path: Path) -> None:
    _save(tmp_path / "one.xlsx", {"Items": [*HEAD, [1, "Sword", 10], [2, "Axe", 12]]})
    _save(tmp_path / "split" / "a.xlsx", {"Items@A": [*HEAD, [2, "Axe", 12]]})
    _save(tmp_path / "split" / "b.xlsx", {"Items@B": [*HEAD, [1, "Sword", 10]]})
    assert _build(tmp_path / "one.xlsx", tmp_path / "o1") == 0
    assert _build(tmp_path / "split", tmp_path / "o2") == 0
    for scope in ("client", "server"):
        assert (tmp_path / "o1" / scope / "Items.json").read_bytes() == \
            (tmp_path / "o2" / scope / "Items.json").read_bytes()


def test_duplicate_key_across_parts_names_both_places(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    _save(tmp_path / "a.xlsx", {"Items@A": [*HEAD, [1, "Sword", 10]]})
    _save(tmp_path / "b.xlsx", {"Items@B": [*HEAD, [1, "Axe", 12]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert "[b.xlsx]Items@B!A4" in error
    assert "[a.xlsx]Items@A!A4" in error


def test_name_case_is_checked_across_parts(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    head = [["Id"], ["ID<name>"], ["all"]]
    _save(tmp_path / "a.xlsx", {"T@A": [*head, ["Sword"]], "T@B": [*head, ["sword"]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    assert "[a.xlsx]T@A!A4" in capsys.readouterr().err


@pytest.mark.parametrize(
    ("other", "message"),
    [
        ([["Id", "Name"], ["ID<int32>", "name"], ["all", "all"]], "'Cost'이 없습니다"),
        ([[*HEAD[0], "Extra"], [*HEAD[1], "int32"], [*HEAD[2], "all"]], "'Extra'이"),
        ([HEAD[0], ["ID<int32>", "name", "float"], HEAD[2]], "'Cost'의 타입"),
        ([HEAD[0], HEAD[1], ["all", "all", "all"]], "'Cost'의 타입·범위"),
    ],
)
def test_parts_must_declare_the_same_fields(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
    other: list[list[object]], message: str,
) -> None:
    _save(tmp_path / "a.xlsx", {"Items@A": [*HEAD, [1, "Sword", 10]]})
    _save(tmp_path / "b.xlsx", {"Items@B": [*other, [2, "Axe", 12]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert message in error
    assert error.startswith("[b.xlsx]Items@B!")
    assert "[a.xlsx]Items@A" in error


def test_enums_cannot_be_split(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    enum = [["Id"], ["ID<name>"], ["all"], ["A"]]
    _save(tmp_path / "a.xlsx", {"<enum>Kind": enum})
    _save(tmp_path / "b.xlsx", {"<enum>Kind": enum, "<enum>Kind@More": enum})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert "[b.xlsx]<enum>Kind!A1" in error and "[a.xlsx]<enum>Kind" in error
    assert "[b.xlsx]<enum>Kind@More!A1" in error


def test_invalid_table_name_before_part_label(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    _save(tmp_path / "a.xlsx", {"1Items@A": [*HEAD, [1, "Sword", 10]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    assert "[a.xlsx]1Items@A!A1" in capsys.readouterr().err


def test_hidden_folders_and_lock_files_are_skipped(tmp_path: Path) -> None:
    _save(tmp_path / "Items.xlsx", {"Items": [*HEAD, [1, "Sword", 10]]})
    _save(tmp_path / ".backup" / "Items.xlsx", {"Items@Old": [*HEAD, [1, "Sword", 10]]})
    assert _build(tmp_path, tmp_path / "out") == 0
