"""스키마 파일과 데이터 시트 연결, 나뉜 테이블, [파일]시트 위치 표기 테스트.

여기서는 스키마 파일을 직접 만들고 데이터 워크북은 plain_save로 저장한다(자동 추출 없음).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from conftest import plain_save
from openpyxl import Workbook

from drtable.cli import main
from drtable.schemafile import Schema, render_xlsx

FIELDS = [("Id", "ID<int32>", "all"), ("Name", "name", "all"), ("Cost", "int32", "server")]
NAMES = [name for name, _, _ in FIELDS]
# 데이터 시트의 2·3행은 스키마를 보여 주는 칸이라 빌드가 읽지 않는다.
VIEW = [["(보기)"] * 3, ["(보기)"] * 3]


def _schema(folder: Path, name: str, fields: list[tuple[str, str, str]]) -> Path:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{name}.schema.xlsx"
    path.write_bytes(render_xlsx(Schema("", name, [(0, *field, None) for field in fields])))
    return path


def _enum(folder: Path, name: str, values: list[tuple[object, object, object]]) -> Path:
    folder = folder / "Enums"
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{name}.enum.xlsx"
    path.write_bytes(render_xlsx(Schema("", name, [(0, n, v, None, c) for n, v, c in values], is_enum=True)))
    return path


def _data(path: Path, sheets: dict[str, list[list[object]]]) -> None:
    workbook = Workbook()
    workbook.remove(workbook.active)
    for name, rows in sheets.items():
        sheet = workbook.create_sheet(name)
        for record in rows:
            sheet.append(record)
    path.parent.mkdir(parents=True, exist_ok=True)
    plain_save(workbook, path)


def _build(source: Path, root: Path, *extra: str) -> int:
    return main(["build", "--input", str(source), "--out-cpp", str(root / "cpp"),
                 "--out-client", str(root / "client"), "--out-server", str(root / "server"), *extra])


def _rows(root: Path, scope: str, table: str) -> list[dict]:
    return json.loads((root / scope / f"{table}.json").read_text(encoding="utf-8"))["rows"]


def test_same_sheet_name_in_several_files_is_one_table(tmp_path: Path) -> None:
    data = tmp_path / "data"
    _schema(data, "Items", FIELDS)
    _data(data / "Items.xlsx", {"Items#무기": [NAMES, *VIEW, [1, "Sword", 10]],
                                "Items #방어구": [NAMES, *VIEW, [20, "Mail", 30]],
                                "#메모": [["아무거나"]]})
    # 하위 폴더의 파일도 합쳐지고, 열 순서는 자유다.
    _data(data / "event" / "Summer.xlsx", {"Items#여름": [
        ["Cost", "Id", "Name"], *VIEW, [5, 3, "Fan"]]})
    assert _build(data, tmp_path / "out") == 0
    rows = _rows(tmp_path / "out", "server", "Items")
    assert [(row["Id"], row["Name"], row["Cost"]) for row in rows] == [
        (1, "Sword", 10), (3, "Fan", 5), (20, "Mail", 30)]
    assert list(rows[1]) == ["Id", "Name", "Cost"]
    # 코드는 스키마 파일만 가리키고, 데이터 위치는 manifest에 남는다.
    header = (tmp_path / "out" / "cpp" / "DtItemsRow.h").read_text(encoding="utf-8")
    assert header.startswith("// Generated by DrTableSystem. Do not edit. Source: Items.schema.xlsx\n")
    manifest = json.loads((tmp_path / "out" / "client" / "manifest.json").read_text(encoding="utf-8"))
    entry = next(item for item in manifest["tables"] if item["name"] == "Items")
    assert entry["schema"] == "Items.schema.xlsx"
    assert entry["sources"] == [
        {"file": "Items.xlsx", "sheet": "Items#무기", "rows": 1},
        {"file": "Items.xlsx", "sheet": "Items #방어구", "rows": 1},
        {"file": "event/Summer.xlsx", "sheet": "Items#여름", "rows": 1},
    ]


def test_split_table_matches_unsplit_output(tmp_path: Path) -> None:
    for folder in ("one", "split"):
        _schema(tmp_path / folder, "Items", FIELDS)
    _data(tmp_path / "one" / "Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10], [2, "Axe", 12]]})
    _data(tmp_path / "split" / "a.xlsx", {"Items": [NAMES, *VIEW, [2, "Axe", 12]]})
    _data(tmp_path / "split" / "b.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    assert _build(tmp_path / "one", tmp_path / "o1") == 0
    assert _build(tmp_path / "split", tmp_path / "o2") == 0
    for scope in ("client", "server"):
        assert (tmp_path / "o1" / scope / "Items.json").read_bytes() == \
            (tmp_path / "o2" / scope / "Items.json").read_bytes()


def test_data_edits_never_change_generated_code(tmp_path: Path) -> None:
    _schema(tmp_path / "data", "Items", FIELDS)
    outputs = []
    for run, rows in (("a", [[1, "Sword", 10]]), ("b", [[1, "Axe", 99], [2, "Bow", 5]])):
        _data(tmp_path / "data" / "Items.xlsx", {"Items": [NAMES, ["바뀐 보기"] * 3, [], *rows]})
        assert _build(tmp_path / "data", tmp_path / run) == 0
        outputs.append({p.name: p.read_bytes() for p in (tmp_path / run / "cpp").iterdir()})
    assert outputs[0] == outputs[1]


def test_rows_two_and_three_and_memo_columns_are_ignored(tmp_path: Path) -> None:
    _schema(tmp_path, "Items", FIELDS)
    _data(tmp_path / "Items.xlsx", {"Items": [
        [*NAMES, "#메모"], ["float", "bool", "text", "x"], ["client", "#", "B", "y"],
        [1, "Sword", 10, "메모는 무시"]]})
    assert _build(tmp_path, tmp_path / "out") == 0
    assert _rows(tmp_path / "out", "server", "Items") == [{"Id": 1, "Name": "Sword", "Cost": 10}]


@pytest.mark.parametrize(
    ("header", "cell", "message"),
    [
        ([*NAMES, "Weight"], "D1", "필드 'Weight'이 스키마 [Items.schema.xlsx]Items에 없습니다"),
        (["Id", "Name"], "A1", "필드 'Cost'의 열이 없습니다 (스키마 [Items.schema.xlsx]Items!A4)"),
        ([*NAMES, "Name"], "D1", "필드명 'Name'이 중복되었습니다"),
    ],
)
def test_data_header_must_match_the_schema(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
    header: list[str], cell: str, message: str,
) -> None:
    _schema(tmp_path, "Items", FIELDS)
    _data(tmp_path / "Items.xlsx", {"Items": [header, *VIEW, [1, "Sword", 10, 1]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert f"[Items.xlsx]Items!{cell}: {message}" in error
    assert not (tmp_path / "out").exists()


def test_data_sheet_without_schema(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    _data(tmp_path / "Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    assert "[Items.xlsx]Items!A1: 스키마가 없습니다. 'Items.schema.xlsx'" in capsys.readouterr().err


def test_schema_without_data_is_an_empty_table(tmp_path: Path) -> None:
    _schema(tmp_path, "Items", FIELDS)
    _data(tmp_path / "Other.xlsx", {"#메모": [["x"]]})
    assert _build(tmp_path, tmp_path / "out") == 0
    assert _rows(tmp_path / "out", "client", "Items") == []
    header = (tmp_path / "out" / "cpp" / "DtItemsRow.h").read_text(encoding="utf-8")
    assert header.startswith("// Generated by DrTableSystem. Do not edit. Source: Items.schema.xlsx\n")


def test_duplicate_key_across_files_names_both_places(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    _schema(tmp_path, "Items", FIELDS)
    _data(tmp_path / "a.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    _data(tmp_path / "b.xlsx", {"Items#B": [NAMES, *VIEW, [1, "Axe", 12]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert error.startswith("[b.xlsx]Items#B!A4")
    assert "[a.xlsx]Items!A4" in error


def test_enum_schema_holds_the_values(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    _enum(tmp_path, "Kind", [("A", None, "첫째"), ("B", 5, "둘째"), ("C", None, None)])
    _schema(tmp_path, "Items", [("Id", "ID<int32>", "all"), ("Kind", "EKind", "all")])
    _data(tmp_path / "Data.xlsx", {
        "Items": [["Id", "Kind"], *VIEW, [1, "B"]],
        "<enum>Old": [["Id"], ["ID<name>"], ["all"], ["X"]],
    })
    assert _build(tmp_path, tmp_path / "out") == 0
    enum = (tmp_path / "out" / "cpp" / "EDtKind.h").read_text(encoding="utf-8")
    assert enum.startswith("// Generated by DrTableSystem. Do not edit. Source: Enums/Kind.enum.xlsx / Kind\n")
    assert "A = 0" in enum and "B = 5" in enum and "C = 6" in enum and "둘째" in enum
    # 옛 <enum> 데이터 시트는 읽지 않고 경고만 한다.
    assert "경고: [Data.xlsx]<enum>Old: 열거형 값은 이제 열거형 스키마" in capsys.readouterr().err


@pytest.mark.parametrize(
    ("values", "cell", "message"),
    [
        ([("Bad-Name", None, None)], "A2", "올바르지 않은 열거자 이름"),
        ([("A", None, None), ("A", None, None)], "A3", "중복"),
        ([("A", "x", None)], "B2", "정수가 아닙니다"),
        ([("A", 300, None)], "B2", "uint8"),
        ([("A", 1, None), ("B", 1, None)], "B3", "열거형 값 1가 중복"),
    ],
)
def test_enum_schema_validation(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
    values: list[tuple[object, object, object]], cell: str, message: str,
) -> None:
    _enum(tmp_path, "Kind", values)
    _data(tmp_path / "Data.xlsx", {"#메모": [["x"]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert f"[Enums/Kind.enum.xlsx]Kind!{cell}" in error and message in error


def test_enum_schemas_must_be_in_the_enum_folder(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    (tmp_path / "Kind.enum.xlsx").write_bytes(render_xlsx(Schema("", "Kind", [(0, "A", None, None, None)], is_enum=True)))
    _schema(tmp_path / "Enums", "Items", FIELDS)
    _data(tmp_path / "Data.xlsx", {"#메모": [["x"]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    error = capsys.readouterr().err
    assert "[Kind.enum.xlsx]!A1: 열거형 스키마는 열거형 폴더" in error
    assert "[Enums/Items.schema.xlsx]!A1: 열거형 폴더에는 열거형 스키마" in error


def test_enum_folder_option(tmp_path: Path) -> None:
    folder = tmp_path / "MyEnums"
    folder.mkdir()
    (folder / "Kind.enum.xlsx").write_bytes(render_xlsx(Schema("", "Kind", [(0, "A", None, None, None), (0, "B", 5, None, None)], is_enum=True)))
    _data(tmp_path / "Data.xlsx", {"#메모": [["x"]]})
    assert _build(tmp_path, tmp_path / "out", "--enums", str(folder)) == 0
    enum = (tmp_path / "out" / "cpp" / "EDtKind.h").read_text(encoding="utf-8")
    assert "B = 5" in enum


def test_schema_file_name_must_match(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    (tmp_path / "Wrong.schema.xlsx").write_bytes(render_xlsx(Schema("", "Items", [(0, *FIELDS[0], None)])))
    _data(tmp_path / "Items.xlsx", {"#메모": [["x"]]})
    assert _build(tmp_path, tmp_path / "out") == 1
    assert "[Wrong.schema.xlsx]Items!A1: 이름 'Items'과 파일 이름 'Wrong.schema.xlsx'이 다릅니다" in capsys.readouterr().err


def test_schema_folder_option(tmp_path: Path) -> None:
    _schema(tmp_path / "Schemas", "Items", FIELDS)
    _data(tmp_path / "Data" / "Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    assert _build(tmp_path / "Data", tmp_path / "out", "--schema", str(tmp_path / "Schemas")) == 0


def test_hidden_folders_and_lock_files_are_skipped(tmp_path: Path) -> None:
    _schema(tmp_path, "Items", FIELDS)
    _data(tmp_path / "Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    _data(tmp_path / ".backup" / "Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    _data(tmp_path / "~$Items.xlsx", {"Items": [NAMES, *VIEW, [1, "Sword", 10]]})
    assert _build(tmp_path, tmp_path / "out") == 0


def test_migrate_moves_old_headers_into_schema_files(tmp_path: Path) -> None:
    old = [["Id", "Name", "Kind"], ["ID<int32>", "name", "EKind"], ["all", "all", "all"],
           [1, "Sword", "B"]]
    enum = [["Id", "Value", "Comment", "Label"], ["ID<name>", "int32", "string", "string"],
            ["all", "all", "#", "client"], ["A", 0, "첫째", "에이"], ["B", 3, None, "비"]]
    _data(tmp_path / "Items.xlsx", {"Items": old, "<enum>Kind": enum})
    before = (tmp_path / "Items.xlsx").read_bytes()
    assert main(["migrate", "--input", str(tmp_path)]) == 0
    assert (tmp_path / "Items.schema.xlsx").exists()
    assert (tmp_path / "Enums" / "Kind.enum.xlsx").exists()
    assert (tmp_path / "KindInfo.schema.xlsx").exists()
    assert (tmp_path / "KindInfo.xlsx").exists()
    assert (tmp_path / "Items.xlsx").read_bytes() == before  # 기존 데이터 파일은 건드리지 않는다
    assert _build(tmp_path, tmp_path / "out") == 0
    assert _rows(tmp_path / "out", "server", "Items") == [{"Id": 1, "Name": "Sword", "Kind": "B"}]
    assert _rows(tmp_path / "out", "client", "KindInfo") == [
        {"Id": "A", "Label": "에이"}, {"Id": "B", "Label": "비"}]
    assert "B = 3" in (tmp_path / "out" / "cpp" / "EDtKind.h").read_text(encoding="utf-8")


def test_migrate_into_a_new_schema_folder_puts_enums_below_it(tmp_path: Path) -> None:
    old = [["Id"], ["ID<name>"], ["all"], ["A"]]
    _data(tmp_path / "Tables" / "T.xlsx", {"<enum>Kind": old})
    schemas = tmp_path / "Tables" / "Schemas"  # 아직 없는 폴더
    assert main(["migrate", "--input", str(tmp_path / "Tables"), "--schema", str(schemas)]) == 0
    assert (schemas / "Enums" / "Kind.enum.xlsx").exists()
