//! Schema files bound to data sheets, split tables, and the [File]Sheet location form.
//!
//! These tests write the schema files themselves and save data workbooks plainly.

#[macro_use]
mod common;

use common::*;
use serde_json::json;
use std::fs;
use std::path::Path;

const FIELDS: [(&str, &str, &str); 3] = [("Id", "ID<int32>", "all"), ("Name", "name", "all"), ("Cost", "int32", "server")];

fn names_row() -> Row {
    row!["Id", "Name", "Cost"]
}

/// Rows 2-3 of a data sheet show the schema; the build does not read them.
fn view() -> [Row; 2] {
    [vec![V::from("(보기)"); 3], vec![V::from("(보기)"); 3]]
}

/// A data sheet: header, the two view rows, then data.
fn sheet(header: Row, data: Vec<Row>) -> Vec<Row> {
    let mut rows = vec![header];
    rows.extend(view());
    rows.extend(data);
    rows
}

fn schema(folder: &Path, name: &str, items: &[(&str, &str, &str)]) {
    write_schema(&folder.join(format!("{name}.schema.xlsx")), name, &fields(items));
}

/// An enum schema in folder/Enums.
fn enum_schema(folder: &Path, name: &str, values: Vec<(V, V, V)>) {
    write_enum(&folder.join("Enums").join(format!("{name}.enum.xlsx")), name, &values);
}

fn data(path: &Path, sheets: Vec<(&str, Vec<Row>)>) {
    let mut book = Book::new();
    for (name, rows) in sheets {
        book.add(name, rows);
    }
    book.save_plain(path);
}

fn memo(path: &Path) {
    data(path, vec![("#메모", vec![row!["x"]])]);
}

fn rows(root: &Path, scope: &str, table: &str) -> serde_json::Value {
    json(&root.join(scope).join(format!("{table}.json")))["rows"].clone()
}

fn ids(root: &Path, scope: &str, table: &str) -> Vec<i64> {
    rows(root, scope, table).as_array().unwrap().iter().map(|row| row["Id"].as_i64().unwrap()).collect()
}

fn ev(name: &str, value: V, comment: V) -> (V, V, V) {
    (V::from(name), value, comment)
}

#[test]
fn same_sheet_name_in_several_files_is_one_table() {
    let tmp = Tmp::new();
    let folder = tmp.join("data");
    schema(&folder, "Items", &FIELDS);
    data(&folder.join("Items.xlsx"), vec![
        ("Items#무기", sheet(names_row(), vec![row![1, "Sword", 10]])),
        ("Items #방어구", sheet(names_row(), vec![row![20, "Mail", 30]])),
        ("#메모", vec![row!["아무거나"]]),
    ]);
    // Files in subfolders join too, and the column order is free.
    data(&folder.join("event/Summer.xlsx"), vec![("Items#여름", sheet(row!["Cost", "Id", "Name"], vec![row![5, 3, "Fan"]]))]);
    let out = tmp.join("out");
    assert_eq!(build(&folder, &out, &[]).code, 0);
    let server = rows(&out, "server", "Items");
    assert_eq!(server, json!([
        {"Id": 1, "Name": "Sword", "Cost": 10},
        {"Id": 3, "Name": "Fan", "Cost": 5},
        {"Id": 20, "Name": "Mail", "Cost": 30},
    ]));
    let order: Vec<&String> = server[1].as_object().unwrap().keys().collect();
    assert_eq!(order, ["Id", "Name", "Cost"]);
    // The code names only the schema file; the data places are in the manifest.
    assert!(read(&out.join("cpp/DrItemsRow.h"))
        .starts_with("// Generated by DrTableSystem. Do not edit. Source: Items.schema.xlsx\n"));
    let manifest = json(&out.join("client/manifest.json"));
    let entry = manifest["tables"].as_array().unwrap().iter().find(|item| item["name"] == "Items").unwrap();
    assert_eq!(entry["schema"], "Items.schema.xlsx");
    assert_eq!(entry["sources"], json!([
        {"file": "Items.xlsx", "sheet": "Items#무기", "rows": 1},
        {"file": "Items.xlsx", "sheet": "Items #방어구", "rows": 1},
        {"file": "event/Summer.xlsx", "sheet": "Items#여름", "rows": 1},
    ]));
}

#[test]
fn split_table_matches_unsplit_output() {
    let tmp = Tmp::new();
    for folder in ["one", "split"] {
        schema(&tmp.join(folder), "Items", &FIELDS);
    }
    data(&tmp.join("one/Items.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10], row![2, "Axe", 12]]))]);
    data(&tmp.join("split/a.xlsx"), vec![("Items", sheet(names_row(), vec![row![2, "Axe", 12]]))]);
    data(&tmp.join("split/b.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    assert_eq!(build(&tmp.join("one"), &tmp.join("o1"), &[]).code, 0);
    assert_eq!(build(&tmp.join("split"), &tmp.join("o2"), &[]).code, 0);
    for scope in ["client", "server"] {
        let file = format!("{scope}/Items.json");
        assert_eq!(fs::read(tmp.join("o1").join(&file)).unwrap(), fs::read(tmp.join("o2").join(&file)).unwrap());
    }
}

#[test]
fn data_edits_never_change_generated_code() {
    let tmp = Tmp::new();
    let folder = tmp.join("data");
    schema(&folder, "Items", &FIELDS);
    let mut outputs = Vec::new();
    for (run, data_rows) in [("a", vec![row![1, "Sword", 10]]), ("b", vec![row![1, "Axe", 99], row![2, "Bow", 5]])] {
        let mut sheet_rows = vec![names_row(), vec![V::from("바뀐 보기"); 3], vec![]];
        sheet_rows.extend(data_rows);
        data(&folder.join("Items.xlsx"), vec![("Items", sheet_rows)]);
        let out = tmp.join(run);
        assert_eq!(build(&folder, &out, &[]).code, 0);
        outputs.push(files(&out.join("cpp")));
    }
    assert_eq!(outputs[0], outputs[1]);
}

#[test]
fn rows_two_and_three_and_memo_columns_are_ignored() {
    let tmp = Tmp::new();
    schema(&tmp, "Items", &FIELDS);
    data(&tmp.join("Items.xlsx"), vec![("Items", vec![
        row!["Id", "Name", "Cost", "#메모"],
        row!["float", "bool", "text", "x"],
        row!["client", "#", "B", "y"],
        row![1, "Sword", 10, "메모는 무시"],
    ])]);
    let out = tmp.join("out");
    assert_eq!(build(&tmp, &out, &[]).code, 0);
    assert_eq!(rows(&out, "server", "Items"), json!([{"Id": 1, "Name": "Sword", "Cost": 10}]));
}

#[test]
fn data_header_must_match_the_schema() {
    let cases = [
        (row!["Id", "Name", "Cost", "Weight"], "D1", "필드 'Weight'이 스키마 [Items.schema.xlsx]Items에 없습니다"),
        (row!["Id", "Name"], "A1", "필드 'Cost'의 열이 없습니다 (스키마 [Items.schema.xlsx]Items!A4)"),
        (row!["Id", "Name", "Cost", "Name"], "D1", "필드명 'Name'이 중복되었습니다"),
    ];
    for (header, cell, message) in cases {
        let tmp = Tmp::new();
        schema(&tmp, "Items", &FIELDS);
        data(&tmp.join("Items.xlsx"), vec![("Items", sheet(header, vec![row![1, "Sword", 10, 1]]))]);
        let out = tmp.join("out");
        let result = build(&tmp, &out, &[]);
        assert_eq!(result.code, 1, "{message}");
        assert!(result.stderr.contains(&format!("[Items.xlsx]Items!{cell}: {message}")), "{}", result.stderr);
        assert!(!out.exists());
    }
}

#[test]
fn data_sheet_without_schema() {
    let tmp = Tmp::new();
    data(&tmp.join("Items.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    let result = build(&tmp, &tmp.join("out"), &[]);
    assert_eq!(result.code, 1);
    assert!(result.stderr.contains("[Items.xlsx]Items!A1: 스키마가 없습니다. 'Items.schema.xlsx'"), "{}", result.stderr);
}

#[test]
fn schema_without_data_is_an_empty_table() {
    let tmp = Tmp::new();
    schema(&tmp, "Items", &FIELDS);
    memo(&tmp.join("Other.xlsx"));
    let out = tmp.join("out");
    assert_eq!(build(&tmp, &out, &[]).code, 0);
    assert_eq!(rows(&out, "client", "Items"), json!([]));
    assert!(read(&out.join("cpp/DrItemsRow.h"))
        .starts_with("// Generated by DrTableSystem. Do not edit. Source: Items.schema.xlsx\n"));
}

#[test]
fn duplicate_key_across_files_names_both_places() {
    let tmp = Tmp::new();
    schema(&tmp, "Items", &FIELDS);
    data(&tmp.join("a.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    data(&tmp.join("b.xlsx"), vec![("Items#B", sheet(names_row(), vec![row![1, "Axe", 12]]))]);
    let result = build(&tmp, &tmp.join("out"), &[]);
    assert_eq!(result.code, 1);
    assert!(result.stderr.starts_with("[b.xlsx]Items#B!A4"), "{}", result.stderr);
    assert!(result.stderr.contains("[a.xlsx]Items!A4"));
}

#[test]
fn enum_schema_holds_the_values() {
    let tmp = Tmp::new();
    enum_schema(&tmp, "Kind", vec![
        ev("A", V::E, V::from("첫째")), ev("B", V::from(5), V::from("둘째")), ev("C", V::E, V::E),
    ]);
    schema(&tmp, "Items", &[("Id", "ID<int32>", "all"), ("Kind", "EKind", "all")]);
    data(&tmp.join("Data.xlsx"), vec![("Items", sheet(row!["Id", "Kind"], vec![row![1, "B"]]))]);
    let out = tmp.join("out");
    assert_eq!(build(&tmp, &out, &[]).code, 0);
    let header = read(&out.join("cpp/EDrKind.h"));
    assert!(header.starts_with("// Generated by DrTableSystem. Do not edit. Source: Enums/Kind.enum.xlsx / Kind\n"));
    for part in ["A = 0", "B = 5", "C = 6", "둘째"] {
        assert!(header.contains(part), "{part}");
    }
}

#[test]
fn enum_schema_validation() {
    let cases = [
        (vec![ev("Bad-Name", V::E, V::E)], "A2", "올바르지 않은 열거자 이름"),
        (vec![ev("A", V::E, V::E), ev("A", V::E, V::E)], "A3", "중복"),
        (vec![ev("A", V::from("x"), V::E)], "B2", "정수가 아닙니다"),
        (vec![ev("A", V::from(300), V::E)], "B2", "uint8"),
        (vec![ev("A", V::from(1), V::E), ev("B", V::from(1), V::E)], "B3", "열거형 값 1가 중복"),
    ];
    for (values, cell, message) in cases {
        let tmp = Tmp::new();
        enum_schema(&tmp, "Kind", values);
        memo(&tmp.join("Data.xlsx"));
        let result = build(&tmp, &tmp.join("out"), &[]);
        assert_eq!(result.code, 1, "{message}");
        assert!(result.stderr.contains(&format!("[Enums/Kind.enum.xlsx]Kind!{cell}")), "{}", result.stderr);
        assert!(result.stderr.contains(message), "{}", result.stderr);
    }
}

#[test]
fn enum_schemas_must_be_in_the_enum_folder() {
    let tmp = Tmp::new();
    write_enum(&tmp.join("Kind.enum.xlsx"), "Kind", &[ev("A", V::E, V::E)]);
    schema(&tmp.join("Enums"), "Items", &FIELDS);
    memo(&tmp.join("Data.xlsx"));
    let result = build(&tmp, &tmp.join("out"), &[]);
    assert_eq!(result.code, 1);
    assert!(result.stderr.contains("[Kind.enum.xlsx]!A1: 열거형 스키마는 열거형 폴더"), "{}", result.stderr);
    assert!(result.stderr.contains("[Enums/Items.schema.xlsx]!A1: 열거형 폴더에는 열거형 스키마"));
}

#[test]
fn enum_folder_option() {
    let tmp = Tmp::new();
    let folder = tmp.join("MyEnums");
    write_enum(&folder.join("Kind.enum.xlsx"), "Kind", &[ev("A", V::E, V::E), ev("B", V::from(5), V::E)]);
    memo(&tmp.join("Data.xlsx"));
    let out = tmp.join("out");
    assert_eq!(build(&tmp, &out, &["--enums", &s(&folder)]).code, 0);
    assert!(read(&out.join("cpp/EDrKind.h")).contains("B = 5"));
}

#[test]
fn schema_file_name_must_match() {
    let tmp = Tmp::new();
    write_schema(&tmp.join("Wrong.schema.xlsx"), "Items", &fields(&FIELDS[..1]));
    memo(&tmp.join("Items.xlsx"));
    let result = build(&tmp, &tmp.join("out"), &[]);
    assert_eq!(result.code, 1);
    assert!(result.stderr.contains("[Wrong.schema.xlsx]Items!A1: 이름 'Items'과 파일 이름 'Wrong.schema.xlsx'이 다릅니다"), "{}", result.stderr);
}

#[test]
fn schema_folder_option() {
    let tmp = Tmp::new();
    schema(&tmp.join("Schemas"), "Items", &FIELDS);
    data(&tmp.join("Data/Items.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    let result = build(&tmp.join("Data"), &tmp.join("out"), &["--schema", &s(&tmp.join("Schemas"))]);
    assert_eq!(result.code, 0, "{}", result.stderr);
}

#[test]
fn hidden_folders_and_lock_files_are_skipped() {
    let tmp = Tmp::new();
    schema(&tmp, "Items", &FIELDS);
    for path in ["Items.xlsx", ".backup/Items.xlsx", "~$Items.xlsx"] {
        data(&tmp.join(path), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    }
    assert_eq!(build(&tmp, &tmp.join("out"), &[]).code, 0);
}

#[test]
fn workbooks_saved_without_dimensions() {
    // Files saved by streaming writers carry no sheet size (<dimension>).
    let tmp = Tmp::new();
    schema(&tmp, "Items", &FIELDS);
    let path = tmp.join("Items.xlsx");
    data(&path, vec![("Items", vec![names_row(), vec![], vec![], row![1, "Sword", 10], row![2, "Axe", 12]])]);
    let mut removed = false;
    rewrite_zip(&path, |name, bytes| {
        if !name.starts_with("xl/worksheets/") {
            return bytes;
        }
        let text = String::from_utf8(bytes).unwrap();
        let start = text.find("<dimension").expect("dimension");
        let end = start + text[start..].find("/>").unwrap() + 2;
        removed = true;
        format!("{}{}", &text[..start], &text[end..]).into_bytes()
    });
    assert!(removed);
    let out = tmp.join("out");
    assert_eq!(build(&tmp, &out, &[]).code, 0);
    assert_eq!(ids(&out, "server", "Items"), [1, 2]);
}

#[test]
fn enum_folder_sits_next_to_the_schema_folder() {
    let tmp = Tmp::new();
    let table = tmp.join("Table");
    schema(&table.join("Schema"), "Items", &[("Id", "ID<int32>", "all"), ("Kind", "EKind", "all")]);
    enum_schema(&table, "Kind", vec![ev("A", V::E, V::E), ev("B", V::E, V::E)]); // Table/Enums
    data(&table.join("Items.xlsx"), vec![("Items", sheet(row!["Id", "Kind"], vec![row![1, "B"]]))]);
    data(&table.join("sub/More.xlsx"), vec![("Items#more", sheet(row!["Id", "Kind"], vec![row![2, "A"]]))]);
    let out = tmp.join("out");
    let result = build(&table, &out, &["--schema", &s(&table.join("Schema"))]);
    assert_eq!(result.code, 0, "{}", result.stderr);
    assert!(read(&out.join("cpp/EDrKind.h"))
        .starts_with("// Generated by DrTableSystem. Do not edit. Source: Enums/Kind.enum.xlsx / Kind\n"));
    assert_eq!(ids(&out, "client", "Items"), [1, 2]);
}

#[test]
fn enums_inside_an_explicit_schema_folder_are_rejected() {
    let tmp = Tmp::new();
    let table = tmp.join("Table");
    schema(&table.join("Schema"), "Items", &FIELDS);
    enum_schema(&table.join("Schema"), "Kind", vec![ev("A", V::E, V::E)]); // Table/Schema/Enums is not the enum folder
    data(&table.join("Items.xlsx"), vec![("Items", sheet(names_row(), vec![row![1, "Sword", 10]]))]);
    let result = build(&table, &tmp.join("out"), &["--schema", &s(&table.join("Schema"))]);
    assert_eq!(result.code, 1);
    assert!(result.stderr.contains("열거형 스키마는 열거형 폴더"), "{}", result.stderr);
}
