"""Unreal C++ output."""

from __future__ import annotations

import json
from pathlib import Path

from .emit_json import content_hash
from .excel import DataModel
from .schema import CLIENT_SCOPES, ColumnSchema, EnumSchema, TableSchema
from .values import default_value

DEFAULT_ASSET_BASE = "UPrimaryDataAsset"
DEFAULT_ASSET_BASE_HEADER = "Engine/DataAsset.h"
DEFAULT_ASSET_NAME = "DA_{table}"
CPP_TYPES = {
    "name": "FName",
    "string": "FString",
    "text": "FText",
    "tag": "FGameplayTag",
    "path": "FSoftObjectPath",
}
TYPE_INCLUDES = {
    "text": "Internationalization/Text.h",
    "tag": "GameplayTagContainer.h",
    "path": "UObject/SoftObjectPath.h",
}


def emit_cpp(
    model: DataModel,
    output: Path,
    prefix: str,
    asset_base: str = DEFAULT_ASSET_BASE,
    asset_base_header: str | None = None,
    runtime_header: str | None = None,
    asset_name: str = DEFAULT_ASSET_NAME,
) -> None:
    """Writes the C++ headers.

    With runtime_header, also writes the runtime integration: row lookup and reference
    accessors, one .cpp per table and the registration header.
    """
    output.mkdir(parents=True, exist_ok=True)
    header = asset_base_header or DEFAULT_ASSET_BASE_HEADER
    for enum in model.enums:
        _write(output / f"E{prefix}{enum.name}.h", _enum_header(enum, prefix))
    enums = {enum.name: enum for enum in model.enums}
    for table in model.tables:
        _write(
            output / f"{prefix}{table.name}Row.h",
            _table_header(table, prefix, enums, runtime_header is not None),
        )
        _write(
            output / f"{prefix}{table.name}Table.h",
            _asset_header(table, prefix, asset_base, header),
        )
        if runtime_header:
            _write(
                output / f"{prefix}{table.name}Row.cpp",
                _row_source(table, prefix, runtime_header),
            )
    _write(output / f"{prefix}GeneratedTables.h", _tables_header(model, prefix, enums))
    if runtime_header:
        _write(
            output / f"{prefix}TableRegistration.h",
            _registration_header(model, prefix, asset_name),
        )


def _source_line(source_name: str, sheet: str) -> str:
    return f"// Generated by ue-tablegen. Do not edit. Source: {source_name} / {sheet}\n"


def _enum_header(enum: EnumSchema, prefix: str) -> str:
    lines = [
        _source_line(enum.source_name, enum.sheet).rstrip("\n"),
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        f'#include "E{prefix}{enum.name}.generated.h"',
        "",
        "UENUM(BlueprintType)",
        f"enum class E{prefix}{enum.name} : uint8",
        "{",
    ]
    for value in enum.values:
        suffix = f" // {_cpp_comment(value.comment)}" if value.comment else ""
        lines.append(f"    {value.name} = {value.value},{suffix}")
    lines.extend(["};", ""])
    return "\n".join(lines)


def _table_header(
    table: TableSchema,
    prefix: str,
    enums: dict[str, EnumSchema],
    accessors: bool = False,
) -> str:
    client_columns = [column for column in table.columns if column.scope in CLIENT_SCOPES]
    enum_includes = sorted(
        {column.type_name[1:] for column in client_columns if column.type_name.startswith("E")}
    )
    type_includes = sorted(
        {TYPE_INCLUDES[column.type_name] for column in client_columns if column.type_name in TYPE_INCLUDES}
    )
    lines = [
        _source_line(table.source_name, table.sheet).rstrip("\n"),
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        '#include "Engine/DataTable.h"',
    ]
    lines.extend(f'#include "{header}"' for header in type_includes)
    lines.extend(f'#include "E{prefix}{name}.h"' for name in enum_includes)
    lines.append(f'#include "{prefix}{table.name}Row.generated.h"')
    if accessors:
        # Tables may reference each other: forward-declare target rows here, include them in the .cpp.
        targets = _ref_targets(table)
        if targets:
            lines.append("")
            lines.extend(f"struct F{prefix}{target}Row;" for target in targets)
    lines.extend(
        [
            "",
            "USTRUCT(BlueprintType)",
            f"struct F{prefix}{table.name}Row : public FTableRowBase",
            "{",
            "    GENERATED_BODY()",
            "",
        ]
    )
    for column in table.columns:
        if column.scope not in CLIENT_SCOPES:
            continue
        property_specifiers = (
            "EditAnywhere"
            if column.is_array
            else "EditAnywhere, BlueprintReadOnly"
        )
        metadata = ""
        if column.ref_target:
            metadata = f', meta = (TableRef = "{column.ref_target}"'
            if column.ref_key:
                metadata += f', TableRefKey = "{column.ref_key}"'
            metadata += ")"
        lines.append(
            f'    UPROPERTY({property_specifiers}, Category = "{prefix}|{table.name}"{metadata})'
        )
        declaration = f"{_cpp_type(column, prefix)} {column.name}"
        if column.is_array:
            declaration += f"[{column.array_size}]"
            if any(value is not None for value in column.default_values):
                values = [
                    value if value is not None else default_value(column.type_name, enums)
                    for value in column.default_values
                ]
                initializer = ", ".join(
                    _cpp_value(column.type_name, value, prefix) for value in values
                )
                declaration += f" = {{{initializer}}}"
            else:
                declaration += " = {}"
        else:
            declaration += _cpp_initializer(column, prefix, enums)
        lines.extend([f"    {declaration};", ""])
    if accessors:
        lines.extend(_accessor_declarations(table, prefix))
    lines.extend(["};", ""])
    return "\n".join(lines)


def _client_refs(table: TableSchema) -> list[ColumnSchema]:
    return [
        column
        for column in table.columns
        if column.ref_target and column.scope in CLIENT_SCOPES
    ]


def _client_sub_keys(table: TableSchema) -> list[ColumnSchema]:
    return [column for column in table.sub_keys if column.scope in CLIENT_SCOPES]


def _ref_targets(table: TableSchema) -> list[str]:
    """Other tables this row references (excluding itself), sorted by name."""
    return sorted(
        {column.ref_target for column in _client_refs(table) if column.ref_target != table.name}
    )


def _ref_return(column: ColumnSchema, prefix: str) -> str:
    row = f"F{prefix}{column.ref_target}Row"
    return f"TArray<const {row}*>" if column.ref_key else f"const {row}*"


def _accessor_declarations(table: TableSchema, prefix: str) -> list[str]:
    row = f"F{prefix}{table.name}Row"
    lines = [
        "    // Lookups (generated). Resolved through the TableGenRuntime contract.",
        f"    static const {row}* Find({_cpp_type(table.primary_key, prefix)} Key);",
    ]
    for column in _client_sub_keys(table):
        lines.append(
            f"    static TArray<const {row}*> FindBy{column.name}({_cpp_type(column, prefix)} Key);"
        )
    lines.append(f"    static TConstArrayView<{row}> GetAll();")
    refs = _client_refs(table)
    if refs:
        lines.extend(["", "    // Reference accessors (generated). An empty reference (0 / NAME_None) returns without a lookup."])
    for column in refs:
        argument = "int32 Index" if column.is_array else ""
        lines.append(f"    {_ref_return(column, prefix)} Get{column.name}({argument}) const;")
    lines.append("")
    return lines


def generated_member_names(table: TableSchema) -> list[tuple[str, str]]:
    """Member function names the row struct gets with runtime integration, with the header cell that caused each."""
    primary_cell = table.primary_key.header_cells[0]
    names = [("Find", primary_cell), ("GetAll", primary_cell)]
    names.extend(
        (f"FindBy{column.name}", column.header_cells[0]) for column in _client_sub_keys(table)
    )
    names.extend((f"Get{column.name}", column.header_cells[0]) for column in _client_refs(table))
    return names


def _absent_check(column: ColumnSchema, expression: str) -> str | None:
    """Expression that detects an empty reference. Enum-keyed references cannot be empty, so they have none."""
    if column.type_name in {"int32", "int64"}:
        return f"{expression} == 0"
    if column.type_name == "name":
        return f"{expression}.IsNone()"
    return None


def _row_source(table: TableSchema, prefix: str, runtime_header: str) -> str:
    row = f"F{prefix}{table.name}Row"
    lines = [
        _source_line(table.source_name, table.sheet).rstrip("\n"),
        f'#include "{prefix}{table.name}Row.h"',
    ]
    lines.extend(f'#include "{prefix}{target}Row.h"' for target in _ref_targets(table))
    lines.extend([f'#include "{runtime_header}"', ""])
    lines.extend(
        [
            f"const {row}* {row}::Find({_cpp_type(table.primary_key, prefix)} Key)",
            "{",
            f"    return TableGenRuntime::FindByKey<{row}>(Key);",
            "}",
            "",
        ]
    )
    for column in _client_sub_keys(table):
        lines.extend(
            [
                f"TArray<const {row}*> {row}::FindBy{column.name}({_cpp_type(column, prefix)} Key)",
                "{",
                f'    return TableGenRuntime::FindAllBySubKey<{row}>(FName(TEXT("{column.name}")), Key);',
                "}",
                "",
            ]
        )
    lines.extend(
        [
            f"TConstArrayView<{row}> {row}::GetAll()",
            "{",
            f"    return TableGenRuntime::GetAll<{row}>();",
            "}",
            "",
        ]
    )
    for column in _client_refs(table):
        target_row = f"F{prefix}{column.ref_target}Row"
        empty = "{}" if column.ref_key else "nullptr"
        lookup = f"FindBy{column.ref_key}" if column.ref_key else "Find"
        value = f"{column.name}[Index]" if column.is_array else column.name
        guards = []
        if column.is_array:
            guards.append(f"Index < 0 || Index >= {column.array_size}")
        absent = _absent_check(column, value)
        if absent:
            guards.append(absent)
        argument = "int32 Index" if column.is_array else ""
        lines.extend([f"{_ref_return(column, prefix)} {row}::Get{column.name}({argument}) const", "{"])
        if guards:
            lines.extend(
                [f"    if ({' || '.join(guards)})", "    {", f"        return {empty};", "    }"]
            )
        lines.extend([f"    return {target_row}::{lookup}({value});", "}", ""])
    return "\n".join(lines)


def _registration_header(model: DataModel, prefix: str, asset_name: str) -> str:
    source_names = ", ".join(model.source_files)
    lines = [
        f"// Generated by ue-tablegen. Do not edit. Source: {source_names}",
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        f'#include "{prefix}GeneratedTables.h"',
    ]
    lines.extend(f'#include "{prefix}{table.name}Table.h"' for table in model.tables)
    lines.extend(
        [
            "",
            f"namespace {prefix}GeneratedTables",
            "{",
            "    // The registry provides Register<Row, Asset>(Name, RowsMember, PrimaryKeysMember). Its result",
            "    // must chain WithSchemaHash(Hash), WithContentHash(Hash) and",
            "    // WithSubKey(Name, KeysMember, OffsetsMember, IndicesMember).",
            "    template <typename TRegistry>",
            "    void RegisterAll(TRegistry& Registry)",
            "    {",
        ]
    )
    for table in model.tables:
        row = f"F{prefix}{table.name}Row"
        asset = f"U{prefix}{table.name}Table"
        name = asset_name.replace("{table}", table.name)
        lines.append(
            f"        Registry.template Register<{row}, {asset}>("
            f'TEXT("{name}"), &{asset}::Rows, &{asset}::PrimaryKeys)'
        )
        lines.append(f"            .WithSchemaHash({table.name}SchemaHash)")
        lines.append(f"            .WithContentHash({table.name}ContentHash)")
        for column in _client_sub_keys(table):
            lines.append(
                f'            .WithSubKey(TEXT("{column.name}"), &{asset}::{column.name}_Keys, '
                f"&{asset}::{column.name}_Offsets, &{asset}::{column.name}_Indices)"
            )
        lines[-1] += ";"
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def _asset_header(
    table: TableSchema,
    prefix: str,
    asset_base: str,
    asset_base_header: str,
) -> str:
    """DataAsset class the bake commandlet fills. Indices are computed at build time and stored as-is."""
    client_columns = [column for column in table.columns if column.scope in CLIENT_SCOPES]
    enum_includes = sorted(
        {column.type_name[1:] for column in client_columns if column.type_name.startswith("E")}
    )
    lines = [
        _source_line(table.source_name, table.sheet).rstrip("\n"),
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        f'#include "{asset_base_header}"',
        f'#include "{prefix}{table.name}Row.h"',
    ]
    lines.extend(f'#include "E{prefix}{name}.h"' for name in enum_includes)
    lines.extend(
        [
            f'#include "{prefix}{table.name}Table.generated.h"',
            "",
            "UCLASS(BlueprintType)",
            f"class U{prefix}{table.name}Table : public {asset_base}",
            "{",
            "    GENERATED_BODY()",
            "",
            "public:",
            "    // All rows in one contiguous array, sorted by primary key.",
            f'    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "{prefix}|{table.name}")',
            f"    TArray<F{prefix}{table.name}Row> Rows;",
            "",
            "    // Primary keys in the same order as Rows, searched with a binary search.",
            "    UPROPERTY()",
            f"    TArray<{_cpp_type(table.primary_key, prefix)}> PrimaryKeys;",
            "",
        ]
    )
    for column in table.sub_keys:
        if column.scope not in CLIENT_SCOPES:
            continue
        key_type = _cpp_type(column, prefix)
        lines.extend(
            [
                f"    // Sub key {column.name}: CSR index (sorted keys, bucket offsets, row indices).",
                "    UPROPERTY()",
                f"    TArray<{key_type}> {column.name}_Keys;",
                "",
                "    UPROPERTY()",
                f"    TArray<int32> {column.name}_Offsets;",
                "",
                "    UPROPERTY()",
                f"    TArray<int32> {column.name}_Indices;",
                "",
            ]
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def _tables_header(model: DataModel, prefix: str, enums: dict[str, EnumSchema]) -> str:
    source_names = ", ".join(model.source_files)
    lines = [
        f"// Generated by ue-tablegen. Do not edit. Source: {source_names}",
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        "",
        f"namespace {prefix}GeneratedTables",
        "{",
    ]
    for table in model.tables:
        primary = table.primary_key
        sub_keys = ",".join(column.name for column in table.sub_keys)
        lines.extend(
            [
                f'    inline constexpr TCHAR {table.name}Name[] = TEXT("{table.name}");',
                f'    inline constexpr TCHAR {table.name}PrimaryKey[] = TEXT("{primary.name}");',
                f'    inline constexpr TCHAR {table.name}SubKeys[] = TEXT("{sub_keys}");',
                f'    inline constexpr TCHAR {table.name}SchemaHash[] = TEXT("{table.schema_hash}");',
                f'    inline constexpr TCHAR {table.name}ContentHash[] = TEXT("{content_hash(table, enums)}");',
                "",
            ]
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def _cpp_type(column: ColumnSchema, prefix: str) -> str:
    if column.type_name.startswith("E"):
        return f"E{prefix}{column.type_name[1:]}"
    return CPP_TYPES.get(column.type_name, column.type_name)


def _cpp_initializer(
    column: ColumnSchema,
    prefix: str,
    enums: dict[str, EnumSchema],
) -> str:
    if column.default_values and column.default_values[0] is not None:
        return f" = {_cpp_value(column.type_name, column.default_values[0], prefix)}"
    initializers = {
        "int32": " = 0",
        "int64": " = 0",
        "float": " = 0.0f",
        "double": " = 0.0",
        "bool": " = false",
    }
    if column.type_name in initializers:
        return initializers[column.type_name]
    if column.ref_target and column.type_name == "name":
        return " = NAME_None"
    if column.type_name.startswith("E"):
        enum_name = column.type_name[1:]
        first_value = enums[enum_name].values[0].name
        return f" = E{prefix}{enum_name}::{first_value}"
    return ""


def _cpp_value(type_name: str, value: object, prefix: str) -> str:
    if type_name in {"int32", "int64"}:
        return str(value)
    if type_name == "float":
        text = repr(float(value))
        return f"{text if '.' in text or 'e' in text else text + '.0'}f"
    if type_name == "double":
        text = repr(float(value))
        return text if "." in text or "e" in text else text + ".0"
    if type_name == "bool":
        return "true" if value else "false"
    literal = json.dumps(str(value), ensure_ascii=False)
    if type_name == "name":
        return f"FName(TEXT({literal}))"
    if type_name == "string":
        return f"FString(TEXT({literal}))"
    if type_name == "text":
        return f"FText::FromString(TEXT({literal}))"
    if type_name == "tag":
        # Member initializers can run before the tag table is loaded (e.g. CDO construction);
        # ErrorIfNotFound=true would then trigger ensureAlwaysMsgf, so pass false explicitly.
        return f"FGameplayTag::RequestGameplayTag(FName(TEXT({literal})), false)"
    if type_name == "path":
        return f"FSoftObjectPath(TEXT({literal}))"
    if type_name.startswith("E"):
        return f"E{prefix}{type_name[1:]}::{value}"
    raise ValueError(f"unsupported C++ default value type: {type_name}")


def _cpp_comment(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ")


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")
