// Copyright ldnjin81. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "DrTableAssetBase.generated.h"

/**
 * Base class for every table asset generated by DrTableSystem.
 *
 * The bake commandlet stores the hashes that drtable wrote into the client JSON.
 * - SchemaHash: at load time the registry compares it with the value compiled into the
 *   generated C++. On a mismatch the asset layout no longer matches the code and the
 *   table is not loaded (error).
 * - ContentHash: generated code does not carry it (data edits must not change code).
 *   The bake commandlet uses it to skip unchanged tables and, with -Verify, to fail on
 *   assets that were not re-baked after the data changed. A registration that calls
 *   WithContentHash itself also gets a load-time warning.
 */
UCLASS(Abstract, BlueprintType)
class DRTABLERUNTIME_API UDrTableAssetBase : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	/** Structure hash (fields, key roles, scopes and the enums the table uses). */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DrTable")
	FString SchemaHash;

	/** Hash of the rows and indices that were baked into this asset. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DrTable")
	FString ContentHash;
};
