// Copyright ldnjin81. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "DrTableAssetBase.generated.h"

/**
 * Base class for every table asset generated by DrTableSystem.
 *
 * The bake commandlet stores the hashes that DrTable wrote into the client JSON.
 * At load time the registry compares them with the values compiled into the
 * generated C++ so that a stale asset is detected instead of being read silently:
 * - SchemaHash mismatch: the asset layout no longer matches the code. The table is
 *   not loaded (error).
 * - ContentHash mismatch: the spreadsheet values changed but the asset was not
 *   re-baked. The table is loaded, with a warning.
 */
UCLASS(Abstract, BlueprintType)
class DRTABLERUNTIME_API UDrTableAssetBase : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	/** Structure hash (fields, key roles, scopes and the enums the table uses). */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DrTable")
	FString SchemaHash;

	/** Hash of the rows and indices that were baked into this asset. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "DrTable")
	FString ContentHash;
};
